apiVersion: v1
kind: Service
metadata:
  name: debezium
  namespace: apollo-demo
  labels:
    app: debezium
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: connect-api
  selector:
    app: debezium
