apiVersion: v1
kind: Service
metadata:
  name: categories-query
  namespace: apollo-demo
  labels:
    app: categories-query
spec:
  selector:
    app: categories-query
  ports:
    - port: 8080
      targetPort: 8080
      name: http
