apiVersion: v1
kind: Service
metadata:
  name: categories-mutation
  namespace: apollo-demo
  labels:
    app: categories-mutation
spec:
  selector:
    app: categories-mutation
  ports:
    - port: 8080
      targetPort: 8080
      name: http
