apiVersion: v1
kind: Service
metadata:
  name: apollo-router
  namespace: apollo-demo
  labels:
    app: apollo-router
spec:
  type: NodePort
  selector:
    app: apollo-router
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
      name: http
    - port: 8088
      targetPort: 8088
      name: health
    - port: 9090
      targetPort: 9090
      name: metrics
