apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: apollo-demo
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  POSTGRES_DB: apollodemo
